### ISSUE TITLE
Inline embedding doesn't work without quotes

### ISSUE THREAD

**Issue by lerayne** [G33kLabs/gulp-inline-base64#2]
Tested on win 10.

Inline transformer only works if url is taken into quotes, line this: url("../images/logo.png"). Is it intentional? Either way, in documentation there is an example, showing the usecase without quotes

**Comment by G33kLabs** [comment]
Are you sure ?
The regex line 15 is : 

```
/url\([|\ |\'|\"](.*?)[|\ |\'|\"](|\,(.*?))\)/g
```

So it takes no quote, simple or double quote

**Comment by lerayne** [comment]
https://jsfiddle.net/foe92o0t/
You placed spaces there so it requires a URL to be wrapped in either singuar quotes, double quotes or spaces.

**Comment by lerayne** [comment]
That would be a valid regexp: `/url\((|\ |\'|\")(.*?)(|\ |\'|\")(|\,(.*?))\)/g`

**Comment by insekticid** [comment]
same problem here
